version: '3'
services:
  webserver:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    entrypoint: "/bin/sh"
    command: ["-c", "truffle migrate && npm run dev"]
    networks:
      ethereum:
        ipv4_address: 172.28.1.0
    ports:
    - "3000:3000"
    - "3001:3001"
    depends_on:
    - miner1
  miner1:
    build:
      context: .
      dockerfile: docker/miner.Dockerfile
    entrypoint: "/bin/sh"
    environment:
    - NODEKEY_HEX=2e6a1170ac47ce3ba4de62962d6a0fc6624bd1d9a53a0223d91300538f8c77be
    command: ["-c", "mkdir -p /root/.ethereum/geth && cp /static-nodes.json /root/.ethereum/geth && geth init /genesis.json && (geth account import --password /account/password.txt /account/account.txt || echo Account existed already!) && geth --nodiscover --nodekeyhex $${NODEKEY_HEX} --unlock 0x373f339c91fd95fea40eb86f9f9981770ca9300a --password /account/password.txt --networkid=1 --verbosity=3 --mine --minerthreads=1 --targetgaslimit=800000000 --etherbase=0x373F339C91fD95FEA40eB86F9F9981770CA9300a --nat=extip:172.28.1.1  --rpc --rpcaddr=0.0.0.0 --rpcport 8545 --rpcapi 'admin,personal,db,eth,net,web3,txpool,miner,shh,debug'"]
    volumes:
    - miner1:/root/.ethereum
    - miner1hash:/root/.ethash
    ports:
    - "8545:8545"
    networks:
      ethereum:
        ipv4_address: 172.28.1.1
  miner2:
    build:
      context: .
      dockerfile: docker/miner.Dockerfile
    entrypoint: "/bin/sh"
    environment:
    - NODEKEY_HEX=8ac6a34569fd5ed8ee5bd96e18e8ba73af270daefc509e52e52cee127e85e449
    command: ["-c", "mkdir -p /root/.ethereum/geth && cp /static-nodes.json /root/.ethereum/geth && geth init /genesis.json && geth --nodiscover --nodekeyhex $${NODEKEY_HEX} --networkid=1 --verbosity=3 --nat=extip:172.28.1.2 --rpc --rpcaddr=0.0.0.0 --rpcport 8545 --rpcapi 'admin,personal,db,eth,net,web3,txpool,miner,shh,debug'"]
    volumes:
    - miner2:/root/.ethereum
    depends_on:
    - miner1
    networks:
      ethereum:
        ipv4_address: 172.28.1.2
  miner3:
    build:
      context: .
      dockerfile: docker/miner.Dockerfile
    entrypoint: "/bin/sh"
    environment:
    - NODEKEY_HEX=80ff7ca85d8bd5f59dadf78659baf05c28d81a38cc3e7e4078f56b4f547f68de
    command: ["-c", "mkdir -p /root/.ethereum/geth && cp /static-nodes.json /root/.ethereum/geth && geth init /genesis.json && geth --nodiscover --nodekeyhex $${NODEKEY_HEX} --networkid=1 --verbosity=3 --nat=extip:172.28.1.3 --rpc --rpcaddr=0.0.0.0 --rpcport 8545 --rpcapi 'admin,personal,db,eth,net,web3,txpool,miner,shh,debug'"]
    volumes:
    - miner3:/root/.ethereum
    depends_on:
    - miner1
    networks:
      ethereum:
        ipv4_address: 172.28.1.3
networks:
  ethereum:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
volumes:
  miner1:
  miner1hash:
  miner2:
  miner3: 